# Generated by Django 5.2.11 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_registration_completed",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has completed registration (name and password set).",
                verbose_name="registration completed",
            ),
        ),
    ]
